<wsdl:definitions name="LrdPlusSoapBindingImplService" targetNamespace="http://lrdplus.presentation.gbav.gba.nl/">
<wsdl:import location="https://www.bprbzk.nl/piva-v/online/lo3services/adhoc'wsdl=LrdPlus.wsdl" namespace="http://www.bprbzk.nl/GBA/LRDPlus/version1.1"> </wsdl:import>
<wsdl:binding name="LrdPlusSoapBindingImplServiceSoapBinding" type="ns1:LrdPlus">
<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
<wsdl:operation name="changePassword">
<soap:operation soapAction="" style="document"/>
<wsdl:input name="changePassword">
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output name="changePasswordResponse">
<soap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
<wsdl:operation name="vraag">
<soap:operation soapAction="" style="document"/>
<wsdl:input name="vraag">
<soap:body use="literal"/>
</wsdl:input>
<wsdl:output name="vraagResponse">
<soap:body use="literal"/>
</wsdl:output>
</wsdl:operation>
</wsdl:binding>
<wsdl:service name="LrdPlusSoapBindingImplService">
<wsdl:port binding="tns:LrdPlusSoapBindingImplServiceSoapBinding" name="LrdPlusSoapBindingImplPort">
<soap:address location="https://www.bprbzk.nl/piva-v/online/lo3services/adhoc"/>
</wsdl:port>
</wsdl:service>
</wsdl:definitions>